export const ERROR_MESSAGE = {
  INVALID_DEVICE_TYPE: "Invalid device type!",
  SCHEMA_VALIDATION_FAILED: "SCHEMA VALIDATION FAILED",
  USER_NOT_FOUND: "User not found!",
  INTERNAL_SERVER_ERROR: "Internal server error!",
  SERVER_UNAVAILABLE: "Service unavailable",
  SSL_HANDSHAKE_FAILED: "unable to establish a secure connection",
  NETWORK_AUTHENTICATION_REQUIRED: "Network Authentication Required",
  ERROR_CREATING_FIREBASE_TOKEN: "Error creating firebase auth token!",
  INVALID_TOKEN: "Invalid session token or session token expired!",
  NOCONTENT: "No match found",
  UNKNOWN_ERROR: "Backend API to mongo DB timeout",
  ENCRYPTION_ERROR: "Encryption Error",
  UNIDENTIFIED_ERROR: "unidentified error",
  NO_DATA_FOUND: "No data found",
  DOC_NOT_FOUND: "Document not found!",
  HOST_NOT_FOUND_HDFC: "Host Not Found",
  BACKEND_CONNECTION_TIMEOUT_HDFC: "cannot connect to backend service",
  BACKEND_READ_TIMEOUT_HDFC: "cannot read from backend service",
  BAD_URL_HDFC: "Bad URL",
  REQUEST_SCHEMA_VALIDATION_FAILURE_HDFC: "Request Schema Validation Failure",
  RESPONSE_SCHEMA_VALIDATION_FAILURE_HDFC: "Response Schema Validation Failure",
  INTERNAL_SERVICE_FAILURE_HDFC: "Internal service failure",
  NULL_VALUES: "Some Values are missing",
  BAD_REQUEST: "Something in the header or request body was malformed",
  FORBIDDEN: "Forbidden",
  CASBIN_FORBIDDEN: "You do not have permission to access this resource.",
  SYSTEM_SERVER_ERROR_HDFC: "External Server Error",
  SEQUELIZE_CONNECTION_ERROR: "Sequelize Connection Error",
  READ_TIMEOUT_HDFC: "read timeout - gateway",
  CONNECTION_TIMEOUT_HDFC: "connection timeout - gateway",
  UNAUTHORISED: "Unauthorized",
  CSV_FILE_DELETE_ERROR:
    "Email sent successfully but error while deleting file.",
  INVALID_FROM_DATE: "Invalid from-date format.",
  INVALID_TO_DATE: "Invalid to-date format.",
  MANDATORY_FROM_DATE: "from-date is required.",
  LARGER_FROM_DATE_ERROR: "from-date cannot be greater that to-date",
  LOGIN_ACTIVITY_DB_ERROR: "Failed to fetch login activity data from database.",
  DUPLICATE_USER: "Duplicate user",
  EXCEPTION_OCCURED: "Exception Occurred while processing the request",
  NULL_ERROR: "Null error",
  NOT_FOUND: "File or page that the browser is requesting was not found",
  INVALID_REQUEST_HDFC: "Invalid Request Structure",
  EXCEEDED_REQUEST_PAYLOAD_LIMIT_HDFC: "Data size limit has exceeded",
  MISSING_REQUIRED_FIELD_DATA_HDFC: "Mandatory fields missing",
  INVALID_FIELD_LENGTH_HDFC: "Field length exceeded",
  INVALID_JSON_OPEN_CURLY_BRACE_MISSING_HDFC: "Invalid Request Structure",
  INVALID_JSON_END_CURLY_BRACE_MISSING_HDFC: "Invalid Request Structure",
  MISSING_REQUIRED_FIELD_HDFC: "Mandatory fields missing",
  REQUEST_ENCRYPTION_ERROR_HDFC: "Request Encryption Error",
  RESPONSE_ENCRYPTION_ERROR_HDFC: "Response Encryption Error",
  INVALID_REQUEST_STRUCTURE_HDFC: "Invalid Request Structure",
  DATA_INSERTION_FAIL: "Data Insertion fail",
  TOO_MANY_REQUESTS: "Too many requests",
  INVALID_OPERATION: "Invalid Operation",
  INTERNAL_ERROR: "Internal Server Error",
  DUPLICATE_ROLE: "Role already exists for this role name",
  SUCCESS: "Successfully returned",
  ROLE_NOT_FOUND: "Role is not found",
  INVALID_STATUS: "Status is not valid",
  NO_PERMISSIONS_FOR_ROLE: "No permissions for this role are found",
  INVALID_PERMISSIONS: "Permissions are not valid",
  PERMISSION_NOT_FOUND: "One or more permissions not found",
  PERMISSION_ALREADY_ASSIGNED: "permissions already assigned to this role",
  PERMISSIONS_ASSIGNED: "permissions successfully assigned to this role",
  INVALID_CREDENTIALS: "Credentials not found in the users table",
  INVALID_EMAIL: "Email id not found",
  INVALID_PASSWORD: "Invalid Password",
  PASSWORD_EMPTY: "Password should not be empty",
  SUBDOMAINDOESNTEXIST: "Subdomain entered does not exist",
  BRANDNAMEDOESNTEXIST: "Brand does not exist",
  BRANDALREADYEXISTS: "Brand Already exists for the given subdomain",
  BRANDNOTEXIST: "Brand with the Id does not exist",
  EMAIL_ALREADY_EXISTS: "Email already exists in the system",
  MOBILE_ALREADY_EXISTS: "Mobile number already exists in the system",
  INVALID_INPUT: "Invalid input",
  FETCHED_SUCCESSFULLY: "Fetched successfully",
  DOWNLOAD_SUCCESSFULLY: "Downloaded Successfully",
  ADDED_SUCCESSFULLY: "Added successfully",
  UPDATED_SUCCESSFULLY: "Updated successfully",
  DELETED_SUCCESSFULLY: "Deleted successfully",
  FILE_UPLOADED: "File uploaded successfully",
  SOMETHING_WENT_WRONG: "Something went wrong",
  STAMP_NOT_FOUND: "Stamp quantity is unavailable, please order stamp papers",
  AUTH_FAILED: "Authentication failed!",
  TOKEN_MISSING: "Authentication token missing!",
  AUTH_SERVICE_DOWN: "Authentication service error!",
  INVALID_AUTH: "Invalid Auth",
  SOCKET_AUTH_ERROR: "Error while authenticating socket connection!",
  NOT_FOUND_MESSAGE: "Not found!",
  REALM_EXISTS: "Realm already exists",
  REALM_NOT_FOUND: "Realm not found.",
  KEYCLOAK_DB_ERROR: "Error while inserting data into Keycloak DB",
  REALM_CREATED_SUCCESSFULLY: "Realm created Successfully",
  REALM_CREATION_ERROR: "Error while creating Realm",
  USER_CREATED_SUCCESSFULLY: "User created Successfully",
  USER_EXISTS: "User with the same email or username already exists",
  USER_CREATION_ERROR: "Error while creating User",
  USER_UPDATED_SUCCESSFULLY: "User updated Successfullly",
  USER_UPDATION_ERROR: "Error while updating User",
  USER_DELETED_SUCCESSFULLY: "User deleted Successfullly",
  USER_DELETION_ERROR: "Error while deleting User",
  PASSWORD_SET_SUCCESSFULLY: "Password set successfully",
  PASSWORD_UPDATION_ERROR: "Error while updating password",
  WRONG_PASSWORD: "Wrong password",
  GLOBAL_SETTING_NOT_FOUND: "Global setting not found!",
  DELETE_STATUS: "Cannot delete an enabled billing profile",
  OTP_EXPIRED: "OTP Expired",
  REQUEST_TYPE_ERROR: 'Request type must be "email", "mobile".',
  OTP_NOT_FOUND: "OTP record not found with the provided otpId.",
  OTP_RECORD_NOT_FOUND: "OTP record not found",
  INVALID_OTP: "Wrong OTP",
  OTP_VERIFIED: "OTP Verified",
  KEYCLOACK_FAILED: "Failed to retrieve Keycloak tokens",
  TRY_AGAIN_LATER: "Too many resend attempts. Please try again later",
  OTP_SENT_SUCCESSFULLY: "OTP sent successfully",
  OTP_SENT_FAILED: "Failed to send OTP",
  SENT_FOR_APPROVAL: "Request Send for Approval Successfully.",
  HOST_ERROR: "Please Provide Correct  SMTP Host Address",
};
