-- AlterTable
ALTER TABLE "SalesVisit" ADD COLUMN     "activity_type" TEXT,
ADD COLUMN     "additional_remarks" TEXT,
ADD COLUMN     "client_type" TEXT,
ADD COLUMN     "current_status" TEXT,
ADD COLUMN     "discussion_summary" TEXT,
ADD COLUMN     "expected_business_value" INTEGER,
ADD COLUMN     "expected_closure_date" TEXT,
ADD COLUMN     "lead_priority" TEXT,
ADD COLUMN     "management_support_required" TEXT,
ADD COLUMN     "meeting_photo" TEXT,
ADD COLUMN     "next_followup_date" TEXT,
ADD COLUMN     "order_closed" TEXT,
ADD COLUMN     "proposal_sent" TEXT,
ADD COLUMN     "reporting_location" TEXT,
ADD COLUMN     "type" TEXT;
